server:
  port: 9002
spring:
  application:
    name: stream-2
  cloud:
    stream:
      bindings:
        input:
          destination: queue.log.messages
          binder: local_rabbit
          group: logMessageConsumers
        output:
          destination: queue.log.messages
          binder: local_rabbit
      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: demo
                password: demo

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8071/eureka,http://localhost:8072/eureka




